### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by ashniazi** [dasundev/filament-access-secret#10]
Hi, 

I'm on Laravel 10.34.2, running filament 3.1. Installed v2.1.1 of this repo.

Published config file, added the secret to the ENV, added middleware to the top of the list for AdminPanelProvider. However the default admin url is still accessible without the key.

Any ideas?

**Comment by dasundev** [comment]
Hmm... Unbelievable. I will look into this.

**Comment by ashniazi** [comment]
@dasundev it randomly started working today on one of my deployments. May be cache related? But now its working well!

**Comment by dasundev** [comment]
> @dasundev it randomly started working today on one of my deployments. May be cache related? But now its working well!

Oh, Okay! Then it probably a cache issue. 

Thanks for the confirmation!
