### ISSUE TITLE
Error when installing the Access Secret plugin

### ISSUE THREAD

**Issue by rcvieiragames** [dasundev/filament-access-secret#5]
Hello,

I am having this error when installing your plugin:

In FilamentAccessSecretServiceProvider.php line 12: 
Class "Filament\PluginServiceProvider" not found

I'm using:

"filament/filament": "^3.0-stable"
"laravel/framework": "^10.10"

Thanks.

**Comment by zynfly** [comment]
I got this error also.

**Comment by dasundev** [comment]
@rcvieiragames Thanks for the update. I will fix it soon.
